use crate::config::Paths;
use crate::printer::Printer;
use anyhow::{Context, Result};
use colored::Colorize;
use std::collections::HashSet;
use std::fs::{File, OpenOptions};
use std::io::{BufRead, BufReader, Write};
use std::path::Path;

pub struct Dedupe;

impl Dedupe {
    pub fn deduplicate_all_reports(paths: &Paths, output_file: Option<&str>) -> Result<String> {
        let mut all_indicators = HashSet::new();
        let mut report_stats = Vec::new();

        // Collect indicators from all reports
        let reports = vec![
            ("Payload Domains", &paths.payload_report),
            ("AMP Report", &paths.amp_report),
            ("C2 Servers", &paths.c2_report),
            ("Top 100", &paths.top_100),
            ("Hex Report", &paths.hex_report),
            ("URLHaus Malware Downloads", &paths.haus_mal_down),
            ("PhishTank", &paths.phish_tank),
        ];

        for (name, path) in &reports {
            if path.exists() {
                match Self::collect_indicators(path, &mut all_indicators) {
                    Ok((count, unique)) => {
                        report_stats.push((name.to_string(), count, unique));
                    }
                    Err(e) => {
                        Printer::warning(&format!("Failed to process {}: {}", name, e));
                        report_stats.push((name.to_string(), 0, 0));
                    }
                }
            } else {
                report_stats.push((name.to_string(), 0, 0));
            }
        }

        // Create output file
        let output = output_file.unwrap_or("MasterList.txt");
        let output_path = Path::new(output);
        
        let mut file = OpenOptions::new()
            .create(true)
            .truncate(true)
            .write(true)
            .open(output_path)
            .context("Failed to create output file")?;

        // Write header
        writeln!(file, "# Master List - Deduplicated Indicators")?;
        writeln!(file, "# Generated by malScraper")?;
        writeln!(file, "# Total Unique Indicators: {}", all_indicators.len())?;
        writeln!(file, "#")?;

        // Write sorted indicators
        let mut sorted_indicators: Vec<&String> = all_indicators.iter().collect();
        sorted_indicators.sort();

        for indicator in &sorted_indicators {
            writeln!(file, "{}", indicator)?;
        }

        // Display summary
        Self::display_summary(&report_stats, all_indicators.len());

        Ok(output.to_string())
    }

    fn collect_indicators(
        path: &Path,
        all_indicators: &mut HashSet<String>,
    ) -> Result<(usize, usize)> {
        let file = File::open(path)
            .with_context(|| format!("Failed to open report file: {:?}", path))?;
        let reader = BufReader::new(file);
        let mut total_count = 0;
        let mut new_count = 0;

        for (line_num, line_result) in reader.lines().enumerate() {
            let line = line_result
                .with_context(|| format!("Failed to read line {} from {:?}", line_num + 1, path))?;
            let trimmed = line.trim();
            
            if trimmed.is_empty() || trimmed.starts_with('#') {
                continue;
            }

            total_count += 1;
            if all_indicators.insert(trimmed.to_string()) {
                new_count += 1;
            }
        }

        Ok((total_count, new_count))
    }

    fn display_summary(report_stats: &[(String, usize, usize)], total_unique: usize) {
        crate::utils::clear_screen();
        Printer::header("DEDUPLICATION SUMMARY", " :: ");
        println!();

        println!("{}", "REPORT STATISTICS".cyan().bold());
        println!();

        let mut total_indicators = 0;
        let mut total_new = 0;

        for (name, count, new) in report_stats {
            total_indicators += count;
            total_new += new;
            
            if *count > 0 {
                println!("  {}", name.cyan());
                println!("    Total Indicators: {}", count.to_string().yellow());
                if *new < *count {
                    println!("    New Unique: {}", new.to_string().green());
                    println!("    Duplicates: {}", (count - new).to_string().red());
                } else {
                    println!("    New Unique: {}", new.to_string().green());
                }
                println!();
            } else {
                println!("  {} - {}", name.cyan(), "Not found".yellow());
                println!();
            }
        }

        println!("{}", "SUMMARY".cyan().bold());
        println!("  Total Indicators Processed: {}", total_indicators.to_string().yellow());
        println!("  Total Unique Indicators: {}", total_unique.to_string().green());
        if total_indicators > total_unique {
            println!(
                "  Total Duplicates Removed: {}",
                (total_indicators - total_unique).to_string().red()
            );
        }
        println!();
    }

    #[allow(dead_code)]
    pub fn show_unique_count(paths: &Paths) -> Result<()> {
        let mut all_indicators = HashSet::new();

        let reports = vec![
            ("Payload Domains", &paths.payload_report),
            ("AMP Report", &paths.amp_report),
            ("C2 Servers", &paths.c2_report),
            ("Top 100", &paths.top_100),
            ("Hex Report", &paths.hex_report),
            ("URLHaus Malware Downloads", &paths.haus_mal_down),
            ("PhishTank", &paths.phish_tank),
        ];

        let mut report_counts = Vec::new();

        for (name, path) in &reports {
            if path.exists() {
                let (total, unique) = Self::collect_indicators(path, &mut all_indicators)?;
                report_counts.push((name.to_string(), total, unique));
            } else {
                report_counts.push((name.to_string(), 0, 0));
            }
        }

        crate::utils::clear_screen();
        Printer::header("UNIQUE INDICATORS COUNT", " :: ");
        println!();

        println!("{}", "REPORT COUNTS".cyan().bold());
        println!();

        let mut total_indicators = 0;
        for (name, count, _) in &report_counts {
            total_indicators += count;
            if *count > 0 {
                println!("  {}: {}", name.cyan(), count.to_string().yellow());
            } else {
                println!("  {}: {}", name.cyan(), "Not found".yellow());
            }
        }

        println!();
        println!("{}", "SUMMARY".cyan().bold());
        println!("  Total Indicators: {}", total_indicators.to_string().yellow());
        println!("  Unique Indicators: {}", all_indicators.len().to_string().green());
        if total_indicators > all_indicators.len() {
            println!(
                "  Duplicates: {}",
                (total_indicators - all_indicators.len()).to_string().red()
            );
        }
        println!();

        Ok(())
    }
}

